### ISSUE TITLE
프로젝트 기본 세팅

### ISSUE THREAD

**Issue by jsh612** [dev-fath/chris-p-bacon#20]
### 작업 상세
- [x] 구조 설정
- [x] 기초 필요 라이브러리 세팅

### 비고
- 무경님의 임시 프로젝트 기반 작업
   - https://www.figma.com/file/jSLWK4umDFxKJcvKZrGs6q/pjt-EVC?node-id=0%3A1&t=eRhDjxjUexz6w6he-1

**Comment by jsh612** [comment]
@dev-fath  추가 작업 사항없으시면 체크후 해당 이슈 닫아도 될까요?

**Comment by dev-fath** [comment]
일단 이정도로 끝내도 될거같아요 
근데 제가 올린건 슬랙에 알림이 뜨는데 승호님이 올린건 안뜨네요

**Comment by dev-fath** [comment]
베이스 작업에 스타일드컴포넌트까지 넣어서 완료처리하겠습니다

**Comment by jsh612** [comment]
> 일단 이정도로 끝내도 될거같아요 근데 제가 올린건 슬랙에 알림이 뜨는데 승호님이 올린건 안뜨네요

댓글 알림이요???
