### ISSUE TITLE
[테마] 폰트, 색상코드 정의

### ISSUE THREAD

**Issue by dev-fath** [dev-fath/chris-p-bacon#22]
- [x] 기본폰트 추가
- [x] Primary 색상코드 추가
- [x] Secondary 색상코드 추가
- [x] Grayscale 색상코드 추가
- [x] 백그라운드 색상코드 추가

**Comment by dev-fath** [comment]
투루 색상코드 따서 쓸까 하는데 괜찮을까요? @jsh612

**Comment by jsh612** [comment]
> 투루 색상코드 따서 쓸까 하는데 괜찮을까요? @jsh612

네 !!
