### ISSUE TITLE
레이아웃_헤더

### ISSUE THREAD

**Issue by jsh612** [dev-fath/chris-p-bacon#8]
### 작업 상세
- [x] 헤더 영역 추가
- [x] 로고 추가

### 비고
- EV 임시 프로젝트 기반 작업

**Comment by jsh612** [comment]
@dev-fath  권한이 없어서인지 작업자 할당이랑 라벨 수정이 안되요

**Comment by dev-fath** [comment]
작업자 할당 수정 되나요 ?

**Comment by jsh612** [comment]
> 작업자 할당 수정 되나요 ?

네 잘됩니다.

**Comment by dev-fath** [comment]
ㅅㄷㄴㅅ

**Comment by dev-fath** [comment]
ㅅㄷㄴㅅ

**Comment by dev-fath** [comment]
테스트

**Comment by jsh612** [comment]
임시 이슈 -> 불필요하여 제거
